services:
  orchestrator:
    build: .
    volumes:
      - ./shared-data:/app/data

  capitalize-worker:
    build: .
    command: python worker.py --task capitalize
    volumes:
      - ./shared-data:/app/data

  reverse-worker:
    build: .
    command: python worker.py --task reverse
    volumes:
      - ./shared-data:/app/data

  consonant-worker:
    build: .
    command: python worker.py --task count_consonants
    volumes:
      - ./shared-data:/app/data

  vowel-worker:
    build: .
    command: python worker.py --task vowel_random
    volumes:
      - ./shared-data:/app/data
